v0.2 bugfixes
still error:
Error CS1061: 'ItemWebService' does not contain a definition for 'AddToCart' and no accessible extension method 'AddToCart' accepting a first argument of type 'ItemWebService' could be found (are you missing a using directive or an assembly reference?)
ProjectPsd_Frontend\Controllers\ItemController.cs